version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=500
      - NEXT_WEBPACK_USEPOLLING=1
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: unless-stopped
    user: "0:0"
    command: ["npm", "run", "dev"]     

volumes:
  node_modules: