version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production  
    ports:
      - '4000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    # Production restart policy
    restart: always
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    # Security options
    security_opt:
      - no-new-privileges:true
    # Read-only root filesystem for security
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache