export const specTemplates = [
  {
    id: "tops",
    name: "Tops/T-shirts",
    specs: [
      {
        header: "Chest Width",
        measurementType: "Width",
        location: "Chest",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Shoulder Width",
        measurementType: "Width",
        location: "Shoulder",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Sleeve Length",
        measurementType: "Length",
        location: "Sleeve",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Body Length",
        measurementType: "Length",
        location: "Body",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Armhole Depth",
        measurementType: "Depth",
        location: "Armhole",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Hem Width",
        measurementType: "Width",
        location: "Hem",
        leftValue: "",
        rightValue: "",
      },
    ],
  },
  {
    id: "shirts",
    name: "Formal Shirts",
    specs: [
      {
        header: "Collar Size",
        measurementType: "Size",
        location: "Collar",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Chest Width",
        measurementType: "Width",
        location: "Chest",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Waist Width",
        measurementType: "Width",
        location: "Waist",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Shoulder Width",
        measurementType: "Width",
        location: "Shoulder",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Sleeve Length",
        measurementType: "Length",
        location: "Sleeve",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Cuff Width",
        measurementType: "Width",
        location: "Cuff",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Body Length",
        measurementType: "Length",
        location: "Body",
        leftValue: "",
        rightValue: "",
      },
    ],
  },
  {
    id: "bottoms",
    name: "Pants/Trousers",
    specs: [
      {
        header: "Waist Width",
        measurementType: "Width",
        location: "Waist",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Hip Width",
        measurementType: "Width",
        location: "Hip",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Thigh Width",
        measurementType: "Width",
        location: "Thigh",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Inseam Length",
        measurementType: "Length",
        location: "Inseam",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Outseam Length",
        measurementType: "Length",
        location: "Outseam",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Leg Opening",
        measurementType: "Width",
        location: "Leg Opening",
        leftValue: "",
        rightValue: "",
      },
    ],
  },
  {
    id: "skirts",
    name: "Skirts",
    specs: [
      {
        header: "Waist Width",
        measurementType: "Width",
        location: "Waist",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Hip Width",
        measurementType: "Width",
        location: "Hip",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Length",
        measurementType: "Length",
        location: "Skirt",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Hem Width",
        measurementType: "Width",
        location: "Hem",
        leftValue: "",
        rightValue: "",
      },
    ],
  },
  {
    id: "dresses",
    name: "Dresses",
    specs: [
      {
        header: "Chest Width",
        measurementType: "Width",
        location: "Chest",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Waist Width",
        measurementType: "Width",
        location: "Waist",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Hip Width",
        measurementType: "Width",
        location: "Hip",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Shoulder Width",
        measurementType: "Width",
        location: "Shoulder",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Sleeve Length",
        measurementType: "Length",
        location: "Sleeve",
        leftValue: "",
        rightValue: "",
      },
      {
        header: "Total Length",
        measurementType: "Length",
        location: "Dress",
        leftValue: "",
        rightValue: "",
      },
    ],
  },
];
